[package]
name = "anyrag-html"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
reqwest = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
md5 = { workspace = true }

# Crate-specific dependencies
html2md = "0.2.15"
scraper = "0.24.0"
