[package]
name = "html"
version = "0.1.0"
edition = "2024"

[dependencies]
html2md = "0.2.15"
md5 = "0.7.0"
regex = "1.11.2"

reqwest = "0.12.5"
tokio = {version = "1", features = ["full"]}
scraper = "0.24.0"
