# Configuration for the Google Gemini API
embedding:
  api_url: "${EMBEDDINGS_API_URL}"
  model_name: "gemini-embedding-001"

providers:
  gemini_default:
    provider: "gemini"
    api_url: "${AI_API_URL}"
    api_key: "${AI_API_KEY}"
    model_name: "gemini-2.5-flash-lite"

  local_fast:
    provider: "local"
    api_url: "http://localhost:1234/v1/chat/completions"
    api_key: null
    model_name: "gemma-2-9b-it-mlx"
