# Configuration for a local AI provider (e.g., Ollama, LM Studio)
embedding:
  api_url: "${EMBEDDINGS_API_URL}"
  model_name: "text-embedding-qwen3-embedding-8b"

providers:
  local_default:
    provider: "local"
    api_url: "${AI_API_URL}"
    api_key: null
    model_name: "gemma-2-9b-it-mlx"

# tasks section is intentionally left blank.
# The default prompts are loaded from `config.prompt.yml`.
# You can override specific tasks by creating a `prompt.yml` file.
tasks: {}
