# Configuration for the Google Gemini API
embedding:
  api_url: "${EMBEDDINGS_API_URL}"
  model_name: "gemini-embedding-001"

providers:
  gemini_default:
    provider: "gemini"
    api_key: "${AI_API_KEY}"
    model_name: "gemini-2.5-flash-lite"

  local_default:
    provider: "local"
    api_url: "${LOCAL_AI_API_URL}"
    api_key: null
    model_name: "qwen3-coder-30b-a3b-instruct-mlx"
